# Generated by Django 2.1.15 on 2020-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200827_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
